server:
  port: 8080
spring:
  application:
    name: security
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    content-type: text/html
    cache: false
    prefix: classpath:/html/
    suffix: .html
  resources:
    static-locations: classpath:/static/
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test
      username: root
      password: ciskwtrs321